import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { originalContent, targetQuery, targetUrl, projectId, competitorUrls = [] } = await req.json();

    if (!originalContent || !targetQuery || !targetUrl || !projectId) {
      throw new Error("originalContent, targetQuery, targetUrl, and projectId are required");
    }

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) {
      throw new Error("LOVABLE_API_KEY not configured");
    }

    console.log(`Regenerating content for query: ${targetQuery}`);

    const systemPrompt = `You are a world-class SEO content writer with expertise in:
- Creating content that ranks #1 on Google
- Semantic keyword optimization
- E-E-A-T (Experience, Expertise, Authoritativeness, Trustworthiness)
- Content structure and readability
- User intent matching

Your task is to rewrite content to outrank competitors and maximize organic traffic.`;

    const userPrompt = `Target Query: "${targetQuery}"
Target URL: ${targetUrl}

Original Content:
${originalContent}

${competitorUrls.length > 0 ? `Competitor URLs ranking for this query:\n${competitorUrls.join('\n')}\n` : ''}

Rewrite this content to:
1. Rank better for "${targetQuery}" by:
   - Adding relevant semantic keywords naturally
   - Matching search intent perfectly
   - Providing comprehensive coverage of the topic
2. Improve readability and structure:
   - Use clear headings (H2, H3)
   - Break content into scannable sections
   - Add bullet points and lists where appropriate
3. Increase depth and value:
   - Aim for +20-30% more content
   - Add specific examples and data
   - Include actionable takeaways
4. Maintain brand voice and style
5. Optimize for featured snippets and "People Also Ask"

Return ONLY the optimized content in markdown format. Do not include explanations or meta-commentary.`;

    console.log("Calling Gemini for content regeneration...");

    const aiResponse = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt },
        ],
        max_tokens: 16384,
      }),
    });

    if (!aiResponse.ok) {
      const errorText = await aiResponse.text();
      console.error("AI Gateway error:", aiResponse.status, errorText);

      if (aiResponse.status === 429) {
        throw new Error("Rate limit exceeded. Please try again later.");
      }
      if (aiResponse.status === 402) {
        throw new Error("Payment required. Please add credits to your Lovable AI workspace.");
      }

      throw new Error(`AI Gateway error (${aiResponse.status}): ${errorText}`);
    }

    const aiData = await aiResponse.json();
    const regeneratedContent = aiData.choices?.[0]?.message?.content;

    if (!regeneratedContent) {
      throw new Error("No content generated by AI");
    }

    console.log("Content regenerated successfully");

    // Calculate improvements
    const wordCountBefore = originalContent.split(/\s+/).length;
    const wordCountAfter = regeneratedContent.split(/\s+/).length;
    const wordCountIncrease = wordCountAfter - wordCountBefore;
    const percentageIncrease = ((wordCountIncrease / wordCountBefore) * 100).toFixed(1);

    // Save to database
    const supabaseClient = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_ANON_KEY") ?? "",
      {
        global: {
          headers: { Authorization: req.headers.get("Authorization")! },
        },
      }
    );

    const { data: savedRegeneration, error: saveError } = await supabaseClient
      .from("content_regenerations")
      .insert({
        project_id: projectId,
        original_url: targetUrl,
        target_query: targetQuery,
        original_content: originalContent,
        regenerated_content: regeneratedContent,
        regeneration_prompt: userPrompt,
        word_count_before: wordCountBefore,
        word_count_after: wordCountAfter,
        improvements: {
          word_count_increase: wordCountIncrease,
          percentage_increase: percentageIncrease,
          competitor_urls: competitorUrls,
        },
      })
      .select()
      .single();

    if (saveError) {
      console.error("Error saving regeneration:", saveError);
      throw saveError;
    }

    console.log("Regeneration saved to database");

    return new Response(
      JSON.stringify({
        success: true,
        data: savedRegeneration,
      }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  } catch (error) {
    console.error("Error in regenerate-content:", error);
    return new Response(
      JSON.stringify({
        error: error instanceof Error ? error.message : "Unknown error",
      }),
      {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  }
});
